provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  test:
    lang: python3
    handler: ./test
    image: test:latest
    build_options:
    - dev
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
