provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  openfaas-python-executor:
    lang: python3
    handler: ./openfaas-python-executor
    image: openfaas-python-executor:latest
    build_options:
    - dev
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
